### ISSUE TITLE
执行 asciidoctor-pdf-cjk-kai_gen_gothic-install 下载字体总是会超时

### ISSUE THREAD

**Issue by aliang228** [chloerei/asciidoctor-pdf-cjk-kai_gen_gothic#2]
/Users/user/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Operation timed out - connect(2) (Errno::ETIMEDOUT)

**Comment by chloerei** [comment]
要从 github release 下载文件，翻墙了没？

**Comment by aliang228** [comment]
那几个字体包文件很大 可能是我的vpn网络不稳定。要是能把这几个文件缓存到国内就好了

**Comment by chloerei** [comment]
字体文件在这里 https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/tag/v0.1.0-fonts

CN 主题需要的是 RobotoMono 开头和 KaiGenGothicCN 开头的字体文件，你可以尝试用其他工具手工下载到 gem 安装目录的 data/fonts 文件夹内。

**Comment by aliang228** [comment]
好的 多谢
