### ISSUE TITLE
How can I adjust base_font_size?

### ISSUE THREAD

**Issue by jinahya** [chloerei/asciidoctor-pdf-cjk-kai_gen_gothic#4]
Thank you for such a great contribution.

This is not an issue and I'm sorry I couldn't help but asking here.

Is there any way to adjust `base_font_size` other than directly modifying the theme?

Such as `-a base_font_size=9`?

**Comment by chloerei** [comment]
I think the best way is copy and modifying the theme file https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc

You can also try http://wkhtmltopdf.org/ , I found it's simpler than asciidoctor-pdf.

**Comment by jinahya** [comment]
Thanks, mate!
